Cross Account Deploy by Codepipeline

diff --git a/template/awscli/generate_codedeploy_cross_account b/template/awscli/generate_codedeploy_cross_account
--- a/template/awscli/generate_codedeploy_cross_account
+++ b/template/awscli/generate_codedeploy_cross_account
@@ -26,6 +26,11 @@ case $key in
     shift # past argument
     shift # past value
     ;;
+    -c|--cross-account-profile)
+    CROSS_ACCOUNT_PROFILE="$2"
+    shift # past argument
+    shift # past value
+    ;;
     *)    # unknown option
     POSITIONAL+=("$1") # save it in an array for later
     shift # past argument
@@ -36,12 +41,25 @@ set -- "${POSITIONAL[@]}" # restore positional parameters
 
 # Check mandatory field
 if [ -z "$APP_NAME" ]; then
-    echo 'Application name is required'
+    echo 'Application name is required.'
     echo 'Usage:'
-    echo '  generate_codedeploy' 
+    echo '  generate_codedeploy_cross_account' 
     echo '      -n APP_NAME'
     echo '      [-p PLATFORM <default:Server>]'
     echo '      [-d DEPLOYMENT_NAME]'
+    echo '      -c CROSS_ACCOUNT_PROFILE'
+    exit 1
+fi
+
+# Check mandatory field
+if [ -z "$CROSS_ACCOUNT_PROFILE" ]; then
+    echo 'Cross account profile is required.'
+    echo 'Usage:'
+    echo '  generate_codedeploy_cross_account' 
+    echo '      -n APP_NAME'
+    echo '      [-p PLATFORM <default:Server>]'
+    echo '      [-d DEPLOYMENT_NAME]'
+    echo '      -c CROSS_ACCOUNT_PROFILE'
     exit 1
 fi
 
@@ -69,36 +87,39 @@ echo 'Codedeploy creation started...'
 ##############################################
 # Set default codedeploy service role name
 CODEDEPLOY_SERVICE_ROLE='CodeDeployServiceRole'
-./create_codedeploy_service_role $CODEDEPLOY_SERVICE_ROLE
+./create_codedeploy_service_role $CODEDEPLOY_SERVICE_ROLE $CROSS_ACCOUNT_PROFILE
 if [ 0 -ne $? ]; then
     echo "Creating 'codedeploy service role' failed."
     exit 9
 fi
+
 # Set codedeploy service role arn
-CODEDEPLOY_SERVICE_ROLE_ARN="$(aws iam get-role --role-name $CODEDEPLOY_SERVICE_ROLE 2> /dev/null | jq -r '.Role.Arn')"
+CODEDEPLOY_SERVICE_ROLE_ARN="$(aws iam get-role --role-name $CODEDEPLOY_SERVICE_ROLE --profile $CROSS_ACCOUNT_PROFILE 2> /dev/null | jq -r '.Role.Arn')"
 
 ##############################################
 # create application
 ##############################################
 # Get ApplicationId
-CODEDEPLOY_APP_ID="$(aws deploy get-application --application-name $APP_NAME 2> /dev/null | jq -r '.application.applicationId')"
+CODEDEPLOY_APP_ID="$(aws deploy get-application --application-name $APP_NAME --profile $CROSS_ACCOUNT_PROFILE 2> /dev/null | jq -r '.application.applicationId')"
 
 # create application
 if [ -z $CODEDEPLOY_APP_ID ]; then
-    CODEDEPLOY_APP_ID="$(aws deploy create-application --application-name $APP_NAME --compute-platform $PLATFORM | jq -r '.applicationId')"
+    CODEDEPLOY_APP_ID="$(aws deploy create-application --application-name $APP_NAME --compute-platform $PLATFORM --profile $CROSS_ACCOUNT_PROFILE | jq -r '.applicationId')"
     sleep 1
 fi
 
 ##############################################
 # create application deployment group
 ##############################################
+
 # EC2 Type deployment
 if [ "Server" == "$PLATFORM" ]; then
-    DEPLOYMENT_GROUP_FLAG="$(aws deploy list-deployment-groups --application-name $APP_NAME | jq -c --arg deploymentGroup $DEPLOYMENT_NAME '.deploymentGroups[] | contains ($deploymentGroup)')"
+    DEPLOYMENT_GROUP_FLAG="$(aws deploy list-deployment-groups --application-name $APP_NAME --profile $CROSS_ACCOUNT_PROFILE | jq -c --arg deploymentGroup $DEPLOYMENT_NAME '.deploymentGroups[] | contains ($deploymentGroup)')"
     if [ "$DEPLOYMENT_GROUP_FLAG" == true ]; then
         continue
     else
         aws deploy create-deployment-group \
+            --profile $CROSS_ACCOUNT_PROFILE \
             --application-name $APP_NAME \
             --deployment-config-name CodeDeployDefault.OneAtATime \
             --deployment-group-name $DEPLOYMENT_NAME \
